# Generated by Django 4.2 on 2023-05-06 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_student_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='colleg',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='is_avtive',
            new_name='is_active',
        ),
    ]
