# Generated by Django 4.2 on 2023-05-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empl', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emp',
            name='id',
        ),
        migrations.AlterField(
            model_name='emp',
            name='emp_id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
